kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: player-role
  namespace: {{ include "player.ns" . }}
rules:
- apiGroups: [""]
  resources: ["pods/log", "pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames:
    - leaky
  verbs: ["watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: player-bind
  namespace: {{ include "player.ns" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: player-role
subjects:
- kind: Group
  name: ctf-players
